[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version = "2.1.20" }
nexus = { id = "tech.yanand.maven-central-publish", version = "1.3.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
