[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm ", version = "2.1.20" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
